package com.customize.cq.selfsvc.prodOrder.model;

import java.util.Date;

public class ProdOrderPO {
//    /**
//     * This field was generated by Abator for iBATIS.
//     * This field corresponds to the database column NGSH.SH_PROD_NCODE.NCODE
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    private String ncode;
//    
//    /**
//     * This field was generated by Abator for iBATIS.
//     * This field corresponds to the database column NGSH.SH_PROD_NCODE.NAME
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    private String name;
//
//    /**
//     * This field was generated by Abator for iBATIS.
//     * This field corresponds to the database column NGSH.SH_PROD_NCODE.REMARK
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    private String remark;
//
//    /**
//     * This field was generated by Abator for iBATIS.
//     * This field corresponds to the database column NGSH.SH_PROD_NCODE.GROUPID
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    private String groupcolor;
//
//    /**
//     * This field was generated by Abator for iBATIS.
//     * This field corresponds to the database column NGSH.SH_PROD_NCODE.BRANDS
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    private String brands;
//
//    /**
//     * This field was generated by Abator for iBATIS.
//     * This field corresponds to the database column NGSH.SH_PROD_NCODE.EFFTYPE
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    private String efftype;
//
//    /**
//     * This field was generated by Abator for iBATIS.
//     * This field corresponds to the database column NGSH.SH_PROD_NCODE.STATUS
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    private Short status;
//
//    /**
//     * This field was generated by Abator for iBATIS.
//     * This field corresponds to the database column NGSH.SH_PROD_NCODE.STATUSTIME
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    private Date statustime;
//    
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method returns the value of the database column NGSH.SH_PROD_NCODE.NCODE
//     *
//     * @return the value of NGSH.SH_PROD_NCODE.NCODE
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public String getNcode() {
//        return ncode;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method sets the value of the database column NGSH.SH_PROD_NCODE.NCODE
//     *
//     * @param ncode the value for NGSH.SH_PROD_NCODE.NCODE
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public void setNcode(String ncode) {
//        this.ncode = ncode;
//    }
//    
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method returns the value of the database column NGSH.SH_PROD_NCODE.NAME
//     *
//     * @return the value of NGSH.SH_PROD_NCODE.NAME
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public String getName() {
//        return name;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method sets the value of the database column NGSH.SH_PROD_NCODE.NAME
//     *
//     * @param remark the value for NGSH.SH_PROD_NCODE.NAME
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public void setName(String name) {
//        this.name = name;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method returns the value of the database column NGSH.SH_PROD_NCODE.REMARK
//     *
//     * @return the value of NGSH.SH_PROD_NCODE.REMARK
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public String getRemark() {
//        return remark;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method sets the value of the database column NGSH.SH_PROD_NCODE.REMARK
//     *
//     * @param remark the value for NGSH.SH_PROD_NCODE.REMARK
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public void setRemark(String remark) {
//        this.remark = remark;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method returns the value of the database column NGSH.SH_PROD_NCODE.GROUPID
//     *
//     * @return the value of NGSH.SH_PROD_NCODE.GROUPID
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public String getGroupcolor() {
//        return groupcolor;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method sets the value of the database column NGSH.SH_PROD_NCODE.GROUPID
//     *
//     * @param groupid the value for NGSH.SH_PROD_NCODE.GROUPID
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public void setGroupcolor(String groupcolor) {
//        this.groupcolor = groupcolor;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method returns the value of the database column NGSH.SH_PROD_NCODE.BRANDS
//     *
//     * @return the value of NGSH.SH_PROD_NCODE.BRANDS
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public String getBrands() {
//        return brands;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method sets the value of the database column NGSH.SH_PROD_NCODE.BRANDS
//     *
//     * @param brands the value for NGSH.SH_PROD_NCODE.BRANDS
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public void setBrands(String brands) {
//        this.brands = brands;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method returns the value of the database column NGSH.SH_PROD_NCODE.EFFTYPE
//     *
//     * @return the value of NGSH.SH_PROD_NCODE.EFFTYPE
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public String getEfftype() {
//        return efftype;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method sets the value of the database column NGSH.SH_PROD_NCODE.EFFTYPE
//     *
//     * @param efftype the value for NGSH.SH_PROD_NCODE.EFFTYPE
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public void setEfftype(String efftype) {
//        this.efftype = efftype;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method returns the value of the database column NGSH.SH_PROD_NCODE.STATUS
//     *
//     * @return the value of NGSH.SH_PROD_NCODE.STATUS
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public Short getStatus() {
//        return status;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method sets the value of the database column NGSH.SH_PROD_NCODE.STATUS
//     *
//     * @param status the value for NGSH.SH_PROD_NCODE.STATUS
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public void setStatus(Short status) {
//        this.status = status;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method returns the value of the database column NGSH.SH_PROD_NCODE.STATUSTIME
//     *
//     * @return the value of NGSH.SH_PROD_NCODE.STATUSTIME
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public Date getStatustime() {
//        return statustime;
//    }
//
//    /**
//     * This method was generated by Abator for iBATIS.
//     * This method sets the value of the database column NGSH.SH_PROD_NCODE.STATUSTIME
//     *
//     * @param statustime the value for NGSH.SH_PROD_NCODE.STATUSTIME
//     *
//     * @abatorgenerated Fri Oct 28 18:18:30 CST 2011
//     */
//    public void setStatustime(Date statustime) {
//        this.statustime = statustime;
//    }
}