insert into icdpub.T_UCP_STAFFBASICINFO (STAFFID, STAFFNAME, STAFFSTATE, STAFFIDSTATUS, DLEVELID, DLMODULUS, SECONDPOST, DUTYID, SECONDDUTY, PTEAMID, ORGAID, POSTID, STAFFACCOUNT, DISABLEBEGINDATE, DISABLEENDDATE, HOSTEDCCID, PERSONALCFGID, UPDATETIME, BATCHNO, WORKEFFICIENCY, STAFFTYPE, ISMANAGER, HRSTATUS, CREATEDATE, STATUSDATE, REMARK, REGION, BEGINDATE, ENDDATE, RELESTAFFID, TELNO, LOGINTYPE, WORKTYPE, AREAID, EMPLOYEETYPE, ISADMIN)
values ('admin', '自助管理员(测试用)', '1', '01', '', 0.00, '', '', '', '', 'CQ.CQ.C1', '008', 'b30test1', null, null, '001', '', to_date('02-03-2011 18:35:32', 'dd-mm-yyyy hh24:mi:ss'), '', 0, 'OPRT31', 1, 0, to_date('09-10-2008 14:38:29', 'dd-mm-yyyy hh24:mi:ss'), null, '', 230, to_date('01-01-2000', 'dd-mm-yyyy'), to_date('22-12-2012', 'dd-mm-yyyy'), 'b30test1', '15023372987', 'SimpAuth', '1', '', '', '');

insert into icdpub.T_UCP_PASSWORD (STAFFID, PASSWORD, BEGINDATE, ENDDATE, UPDATEDATE, HOSTEDCCID)
values ('admin', '96E79218965EB72C92A549DD5A330112', null, null, to_date('25-01-2011 16:36:41', 'dd-mm-yyyy hh24:mi:ss'), '');

insert into icdpub.T_UCP_STAFFEXTENDINFO (STAFFID, SEX, ISMARRIED, POLITICALSTANDING, JOINPARTYDATE, IDCARDCODE, TELNO, EDUCATION, GRADUATEDATE, UNIVERSITY, MAJOR, JOINDATE, JOINLEN, COMPANYID, DIMISSIONDATE, DOMICILEDPLACE, EMERGLINKMAN1, EMERGENCETELNO1, EMERGLINKMAN2, EMERGENCETELNO2, FAXNO, HOMEADDRESS, POSTALCODE, DWELLING, CERTDESC, PHOTO, STARNUM, BUREAUNO, BIRTHDAY, AGE, NATION, EMPLOYMENTEXPERIENCE, NATIVEPLACE, EDUCATIONEXPERIENCE, FOREIGNLANGUAGE, FOREIGNLANGUAGELEVEL, COMPUTERLEVEL, TYPESPEED, LENGTHOFSERVICE, MOBILEPHONE, EMAILADDRESS, CERTANDDESC, COSHORTTELNUM, BATCHNUM, HOSTEDCCID, REGION, TRAINLEVEL, SKILLLEVEL, TOTALLEVEL, COMITYLEVEL, HOMEPHONE, OPERATORTYPE, NATIVEHOME, NOWPOSTID, TITLE, COUNTYID, OTHERNAME, SERVERTYPE, NOTICETYPE, NOTICECONDITION)
values ('admin', '1', '1', '', null, '', '13983240124', '', null, '', '', null, 0.0, '', null, '', '', '', '', '', '', '', '', '', '', '', '', '', null, 0, '', '', '', '', '', '', '', '', 0, '15023372987', '', '', '', '', '', null, '', '', '', '', '', null, '', '', '', '', '', '', 0, 0);

insert into icdpub.T_UCP_STAFFRESTRICTINFO (STAFFID, ISRESTRICT, STARTTIME, ENDTIME, ENABLEGRPS, GPRSSTARTTIME, GPRSENDTIME, MACMODE, ACCESSFUNC, INVALIDATETIME, ALLOWLOGIN, LOGINSTARTTIME, LOGINENDTIME)
values ('admin', 0, 0, 0, 0, 0, 0, 0, '', to_date('06-06-2040', 'dd-mm-yyyy'), 1, '', '');

insert into icdpub.T_UCP_StaffMac (STAFFID, MACVALUE)
values ('admin', '00-16-EC-71-E2-99');