insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('UniGetBalanceByTelnum_Atsv', 1, null, '', 'ISOFFSET', '1', '', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('UniGetBalanceByTelnum_Atsv', 1, null, '', 'OPCODE', 'arIntQryBalByServnum', '', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('UniGetBalanceByTelnum_Atsv', 2, 0, 'TELNUM=TELNUM&OPERID=OPERID', '', '', '', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('UniGetBalanceByTelnum_Atsv', 3, 0, 'PREPAYTYPE=PREPAYTYPE&CURRBILLFEE=CURRBILLFEE&HISBILLFEE=HISBILLFEE&BALANCE=BALANCE&EXPIREDATE=EXPIREDATE&CONTRACT_BALANCE=CONTRACT_BALANCE&CONTRACT_CANUSE=CONTRACT_CANUSE&CONTRACT_THISUSED=CONTRACT_THISUSED&CONTRACT_DRAWAMT=CONTRACT_DRAWAMT&PRESENT_BALANCE=PRESENT_BALANCE&PRESENT_CANUSE=PRESENT_CANUSE&PRESENT_THISUSED=PRESENT_THISUSED&PRESENT_DRAWAMT=PRESENT_DRAWAMT&CASH_BALANCE=CASH_BALANCE&OTHER_BALANCE=OTHER_BALANCE', '', '', '', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('UniGetBalanceByTelnum_Atsv', 4, null, '100=0', '', '', '', null);

