insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('LogIn_Atsv', 4, null, '100=0', '', '', '返回值转换', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('LogIn_Atsv', 3, 0, 'SUBNAME=SUBNAME&REGION=REGION&REGIONNAME=REGNAME&PRODUCTID=PRODUCTID&PRODUCTNAME=PRODUCTNAME&PRODUCTGROUP=PRODUCTGROUP&VIPTYPE=VIPTYPE&LOGINTYPE=LOGINTYPE&FEEFLAG=FEEFLAG&QUESTION=QUESTION&ANSWER=ANSWER&NEEDCHECKSTR=NEEDCHECKSTR&STATUS=STATUS', '', '', '输出参数转换', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('LogIn_Atsv', 2, 0, 'TELNUM=MSISDN&PASSWORD=PASSWORD&ISCHECKPASS=ISCHECKPASS&OPERID=OPERID&OPERID=OPERID', '', '', '输入参数转换', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('LogIn_Atsv', 1, null, '', 'OPCODE', 'SubsLogIn', '网上营业厅用户登陆验证', null);

