--新增接口操作员配置
delete from SA_DB_ACCAGENTUNIT where agentunit='bsacAtsv';

insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBWH270', '270', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBXF710', '710', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBEZ711', '711', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBXG712', '712', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBHG713', '713', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBHS714', '714', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBXN715', '715', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBJZ716', '716', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBYC717', '717', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBNS718', '718', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBSY719', '719', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBSZ722', '722', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBJM724', '724', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBJH728', '728', 'bsacAtsv');
insert into SA_DB_ACCAGENTUNIT (AGENTUNIT, AGENTNAME, AGENTOPERATOR, AGENTCODE, AGENTTYPE) 
values ('bsacAtsv', '一级BOSS虚拟工号', 'IBWH270', '999', 'bsacAtsv');

--自助终端发送短信通用模板
delete SA_DB_SMTEMPLATE where TEMPLATE_NO = 'Atsv0001';

insert into SA_DB_SMTEMPLATE (TEMPLATE_NO, TEMPLATE_TYPE, DESCRIPTION, SMS_PORT, DISP_FROM, REPORT, VALID_TIME, CONTENT, INTIME, DO_VALID_TIME, BEGINDATE, ENDDATE, PRIORITY, WORKTIME, LONGSMSTYPE, FEETYPE, FEECODE, OVERTIME, DELAYTIME, AUDITSTATUS, ENCPARA)
values ('Atsv0001', 'REC003  ', '自助终端发送短信通用模板', '10086', '10086', '0', 86400, '%1', sysdate, 86400, to_date('01-01-1999', 'dd-mm-yyyy'), to_date('01-01-2099', 'dd-mm-yyyy'), 1, '', 0, '1', '0', 0, 0, 1, '');
