insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('CancleSubsIntServ_Atsv', 1, null, '', 'OPCODE', 'CCEICancleSubsIntServ', '', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('CancleSubsIntServ_Atsv', 2, 0, 'TELNUM=TELNUM&OPERTYPE=OPERTYPE&SOURCE=SOURCE&CHKTYPE=CHKTYPE&FLAG=FLAG&SRPFLAG=SRPFLAG&CANCEL_FLAG=CANCEL_FLAG&DETAILINFO=DETAILINFO&ISNOTIFY=ISNOTIFY&OPERID=OPERID', '', '', '输入参数转换', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('CancleSubsIntServ_Atsv', 3, 0, 'ORDERRESULT=ORDERRESULT&ORDERTIME=ORDERTIME&ORDERFLAG=ORDERFLAG&TIMEOUTS=TIMEOUTS&AFFIRM=AFFIRM&EFFETITIME=EFFETITIME&ABATETIME=ABATETIME', '', '', '', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('CancleSubsIntServ_Atsv', 4, null, '100=0', '', '', '', null);

