insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('CheckResetPassword_Atsv', 4, null, '100=0&101=988706&105=-3003&102=-2020&104=-3001', '', '', '返回值转换', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('CheckResetPassword_Atsv', 3, 0, 'COMMITFLAG=COMMITFLAG&REMINDFLAG=REMINDFLAG&MAXFAILNUM=MAXFAILNUM&CURFAILNUM=CURFAILNUM&REMINDNUM=REMINDNUM&ISFREEZE=ISFREEZE', '', '', '输出参数转换', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('CheckResetPassword_Atsv', 2, 0, 'TELNUM=TELNUM&OLD_PASSWD=OLD_PASSWD&NEW_PASSWD=NEW_PASSWD&CALLERNUM=CALL_NUMBER&ISSENDSMS=ISSENDSMS&FLAG=FLAG&CHKTYPE=CHKTYPE&SUBCMDID=SUBCMDID&ISREMIND=ISREMIND&OPERID=OPERID', '', '', '输入参数转换', null);

insert into int_command_param (COMMANDID, PARAMTYPE, TRANSTYPE, PARAMFMT, PARAMNAME, PARAMVALUE, PARAMDESC, BEGINROW)
values ('CheckResetPassword_Atsv', 1, null, '', 'OPCODE', 'CCEICheckResetPassword', '新客服密码验证及修改', null);

